name: printify-automation
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pandas
  - numpy
  - requests
  - scikit-learn
  - pip
  - pip:
      - colorspacious
      - google-auth
      - google-auth-oauthlib
      - google-api-python-client
      - google-genai
      - pillow
