name: Run Printify Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Use Conda to handle the requirements.yml file
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: test-env
        environment-file: requirements.yml
        python-version: '3.12'
        auto-activate-base: false

    - name: Run Pytest
      shell: bash -el {0} # Important: Tells the shell to use the Conda environment
      env:
        PYTHONPATH: .
      run: |
        pip install pytest # Ensure pytest is available in the env
        pytest printify/tests -v